const fudalist = [
    {
        no: 1,
        kimariji: "あきの",
        normal: "./torifuda/tori_1.png",
        reverse: "./torifuda/tori_r_1.png",
        goro: "あきの つゆ",
        classification: "16枚札　あ",
        upper: "秋の田の かりほの庵の 苫をあらみ",
        lower: "我が衣手は 露にぬれつつ",
        author: "天智天皇",
        goroImage: "089.png",
        studyOrder: 89
    },
    {
        no: 2,
        kimariji: "はるす",
        normal: "./torifuda/tori_2.png",
        reverse: "./torifuda/tori_r_2.png",
        goro: "はるっす ころもほすっす",
        classification: "4枚札　はやよか",
        upper: "春過ぎて 夏来にけらし 白妙の",
        lower: "衣ほすてふ 天の香具山",
        author: "持統天皇",
        goroImage: "030.png",
        studyOrder: 30
    },
    {
        no: 3,
        kimariji: "あし",
        normal: "./torifuda/tori_3.png",
        reverse: "./torifuda/tori_r_3.png",
        goro: "あし ながなが",
        classification: "16枚札　あ",
        upper: "あしびきの 山鳥の尾の しだり尾の",
        lower: "ながながし夜を ひとりかも寝む",
        author: "柿本人麻呂",
        goroImage: "098.png",
        studyOrder: 98
    },
    {
        no: 4,
        kimariji: "たご",
        normal: "./torifuda/tori_4.png",
        reverse: "./torifuda/tori_r_4.png",
        goro: "たごさくは ふじみ",
        classification: "6枚札　たこ",
        upper: "田子の浦に うちいでてみれば 白妙の",
        lower: "富士の高嶺に 雪は降りつつ",
        author: "山部赤人",
        goroImage: "053.png",
        studyOrder: 53
    },
    {
        no: 5,
        kimariji: "おく",
        normal: "./torifuda/tori_5.png",
        reverse: "./torifuda/tori_r_5.png",
        goro: "おくから こえが",
        classification: "7枚札　おわ",
        upper: "奥山に もみぢふみわけ なく鹿の",
        lower: "声聞く時ぞ 秋はかなしき",
        author: "猿丸太夫",
        goroImage: "063.png",
        studyOrder: 63
    },
    {
        no: 6,
        kimariji: "かさ",
        normal: "./torifuda/tori_6.png",
        reverse: "./torifuda/tori_r_6.png",
        goro: "かさ しろ",
        classification: "4枚札　はやよか",
        upper: "かささぎの 渡せる橋に おく霜の",
        lower: "白きをみれば 夜ぞふけにける",
        author: "中納言家持",
        goroImage: "043.png",
        studyOrder: 43
    },
    {
        no: 7,
        kimariji: "あまの",
        normal: "./torifuda/tori_7.png",
        reverse: "./torifuda/tori_r_7.png",
        goro: "あまの みか",
        classification: "16枚札　あ",
        upper: "天の原 ふりさけみれば 春日なる",
        lower: "三笠の山に いでし月かも",
        author: "阿倍仲麻呂",
        goroImage: "092.png",
        studyOrder: 92
    },
    {
        no: 8,
        kimariji: "わがい",
        normal: "./torifuda/tori_8.png",
        reverse: "./torifuda/tori_r_8.png",
        goro: "わがい よをう",
        classification: "7枚札　おわ",
        upper: "わが庵は 都のたつみ しかぞすむ",
        lower: "世をうぢ山と 人はいふなり",
        author: "喜撰法師",
        goroImage: "071.png",
        studyOrder: 71
    },
    {
        no: 9,
        kimariji: "はなの",
        normal: "./torifuda/tori_9.png",
        reverse: "./torifuda/tori_r_9.png",
        goro: "はなの わがみよ",
        classification: "4枚札　はやよか",
        upper: "花の色は うつりにけりな いたづらに",
        lower: "わが身よにふる ながめせしまに",
        author: "小野小町",
        goroImage: "033.png",
        studyOrder: 33
    },
    {
        no: 10,
        kimariji: "これ",
        normal: "./torifuda/tori_10.png",
        reverse: "./torifuda/tori_r_10.png",
        goro: "これ しる",
        classification: "6枚札　たこ",
        upper: "これやこの 行くも帰るも わかれては",
        lower: "しるもしらぬも 逢坂の関",
        author: "蝉丸",
        goroImage: "057.png",
        studyOrder: 57
    },
    {
        no: 11,
        kimariji: "わたのはらや",
        normal: "./torifuda/tori_11.png",
        reverse: "./torifuda/tori_r_11.png",
        goro: "わたのはらや つりぶね",
        classification: "7枚札　おわ",
        upper: "わたの原 八十島かけて こぎいでぬと",
        lower: "人にはつげよ あまのつり舟",
        author: "参議篁",
        goroImage: "075.png",
        studyOrder: 75
    },
    {
        no: 12,
        kimariji: "あまつ",
        normal: "./torifuda/tori_12.png",
        reverse: "./torifuda/tori_r_12.png",
        goro: "あまつ おとめ",
        classification: "16枚札　あ",
        upper: "天つ風 雲のかよひ路 吹きとぢよ",
        lower: "をとめの姿 しばしとどめむ",
        author: "僧正遍昭",
        goroImage: "091.png",
        studyOrder: 91
    },
    {
        no: 13,
        kimariji: "つく",
        normal: "./torifuda/tori_13.png",
        reverse: "./torifuda/tori_r_13.png",
        goro: "つく こいぞ",
        classification: "2枚札　うつしもゆ",
        upper: "つくばねの 峰よりおつる みなの川",
        lower: "恋ぞつもりて 淵となりぬる",
        author: "陽成院",
        goroImage: "011.png",
        studyOrder: 11
    },
    {
        no: 14,
        kimariji: "みち",
        normal: "./torifuda/tori_14.png",
        reverse: "./torifuda/tori_r_14.png",
        goro: "みち みだれそう",
        classification: "5枚札　み",
        upper: "みちのくの しのぶもぢずり 誰ゆゑに",
        lower: "みだれそめにし 我ならなくに",
        author: "河原左大臣",
        goroImage: "046.png",
        studyOrder: 46
    },
    {
        no: 15,
        kimariji: "きみがためは",
        normal: "./torifuda/tori_15.png",
        reverse: "./torifuda/tori_r_15.png",
        goro: "きみがためはの ゆきちゃん",
        classification: "3枚札　いちひき",
        upper: "君がため 春の野に出でて 若菜つむ",
        lower: "わが衣手に 雪はふりつつ",
        author: "光孝天皇",
        goroImage: "028.png",
        studyOrder: 28
    },
    {
        no: 16,
        kimariji: "たち",
        normal: "./torifuda/tori_16.png",
        reverse: "./torifuda/tori_r_16.png",
        goro: "たち まっと",
        classification: "6枚札　たこ",
        upper: "立ちわかれ いなばの山の 峰に生ふる",
        lower: "まつとし聞かば いまかへりこむ",
        author: "中納言行平",
        goroImage: "052.png",
        studyOrder: 52
    },
    {
        no: 17,
        kimariji: "ちは",
        normal: "./torifuda/tori_17.png",
        reverse: "./torifuda/tori_r_17.png",
        goro: "ちは からい",
        classification: "3枚札　いちひき",
        upper: "ちはやぶる 神代もきかず 竜田川",
        lower: "からくれなゐに 水くくるとは",
        author: "在原業平朝臣",
        goroImage: "021.png",
        studyOrder: 21
    },
    {
        no: 18,
        kimariji: "す",
        normal: "./torifuda/tori_18.png",
        reverse: "./torifuda/tori_r_18.png",
        goro: "すの ゆめ",
        classification: "1枚札　むすめふさほせ",
        upper: "住の江の 岸による波 よるさへや",
        lower: "夢のかよひ路 人目よくらむ",
        author: "藤原敏行朝臣",
        goroImage: "002.png",
        studyOrder: 2
    },
    {
        no: 19,
        kimariji: "なにわが",
        normal: "./torifuda/tori_19.png",
        reverse: "./torifuda/tori_r_19.png",
        goro: "なにわが あわで",
        classification: "8枚札　な",
        upper: "難波潟 みじかき蘆の ふしのまも",
        lower: "あはでこの世を すぐしてよとや",
        author: "伊勢",
        goroImage: "083.png",
        studyOrder: 83
    },
    {
        no: 20,
        kimariji: "わび",
        normal: "./torifuda/tori_20.png",
        reverse: "./torifuda/tori_r_20.png",
        goro: "わさび はむ",
        classification: "7枚札　おわ",
        upper: "わびぬれば いまはたおなじ 難波なる",
        lower: "身をつくしても あはむとぞ思ふ",
        author: "元良親王",
        goroImage: "070.png",
        studyOrder: 70
    },
    {
        no: 21,
        kimariji: "いまこ",
        normal: "./torifuda/tori_21.png",
        reverse: "./torifuda/tori_r_21.png",
        goro: "いまこ あり",
        classification: "3枚札　いちひき",
        upper: "今こむと いひしばかりに 長月の",
        lower: "有明の月を まちいでつるかな",
        author: "素性法師",
        goroImage: "020.png",
        studyOrder: 20
    },
    {
        no: 22,
        kimariji: "ふ",
        normal: "./torifuda/tori_22.png",
        reverse: "./torifuda/tori_r_22.png",
        goro: "ふ むべ",
        classification: "1枚札　むすめふさほせ",
        upper: "吹くからに 秋の草木の しをるれば",
        lower: "むべ山風を 嵐といふらむ",
        author: "文屋康秀",
        goroImage: "004.png",
        studyOrder: 4
    },
    {
        no: 23,
        kimariji: "つき",
        normal: "./torifuda/tori_23.png",
        reverse: "./torifuda/tori_r_23.png",
        goro: "つき わがみひとつ",
        classification: "2枚札　うつしもゆ",
        upper: "月みれば ちぢにものこそ かなしけれ",
        lower: "わが身一つの 秋にはあらねど",
        author: "大江千里",
        goroImage: "010.png",
        studyOrder: 10
    },
    {
        no: 24,
        kimariji: "この",
        normal: "./torifuda/tori_24.png",
        reverse: "./torifuda/tori_r_24.png",
        goro: "この もみじ",
        classification: "6枚札　たこ",
        upper: "このたびは ぬさもとりあへず 手向山",
        lower: "もみぢのにしき 神のまにまに",
        author: "菅家",
        goroImage: "059.png",
        studyOrder: 59
    },
    {
        no: 25,
        kimariji: "なにし",
        normal: "./torifuda/tori_25.png",
        reverse: "./torifuda/tori_r_25.png",
        goro: "なにし ひとにし",
        classification: "8枚札　な",
        upper: "名にし負はば 逢坂山の さねかづら",
        lower: "人にしられで 来るよしもがな",
        author: "三条右大臣",
        goroImage: "082.png",
        studyOrder: 82
    },
    {
        no: 26,
        kimariji: "おぐ",
        normal: "./torifuda/tori_26.png",
        reverse: "./torifuda/tori_r_26.png",
        goro: "おぐら みゆき",
        classification: "7枚札　おわ",
        upper: "小倉山 峰のもみぢ葉 心あらば",
        lower: "いまひとたびの みゆきまたなむ",
        author: "貞信公",
        goroImage: "066.png",
        studyOrder: 66
    },
    {
        no: 27,
        kimariji: "みかの",
        normal: "./torifuda/tori_27.png",
        reverse: "./torifuda/tori_r_27.png",
        goro: "みかの いつみき",
        classification: "5枚札　み",
        upper: "みかの原 わきて流るる いづみ川",
        lower: "いつみきとてか 恋しかるらむ",
        author: "中納言兼輔",
        goroImage: "050.png",
        studyOrder: 50
    },
    {
        no: 28,
        kimariji: "やまざ",
        normal: "./torifuda/tori_28.png",
        reverse: "./torifuda/tori_r_28.png",
        goro: "やまざきさんに ひとめぼれ",
        classification: "4枚札　はやよか",
        upper: "山里は 冬ぞさびしさ まさりける",
        lower: "人目も草も かれぬと思へば",
        author: "源宗行朝臣",
        goroImage: "037.png",
        studyOrder: 37
    },
    {
        no: 29,
        kimariji: "こころあ",
        normal: "./torifuda/tori_29.png",
        reverse: "./torifuda/tori_r_29.png",
        goro: "こころあ おき",
        classification: "6枚札　たこ",
        upper: "心当てに 折らばや折らむ 初霜の",
        lower: "おきまどはせる 白菊の花",
        author: "凡河内躬恒",
        goroImage: "061.png",
        studyOrder: 61
    },
    {
        no: 30,
        kimariji: "ありあ",
        normal: "./torifuda/tori_30.png",
        reverse: "./torifuda/tori_r_30.png",
        goro: "ありあ あかてん",
        classification: "16枚札　あ",
        upper: "有明の つれなく見えし 別れより",
        lower: "あかつきばかり うきものはなし",
        author: "壬生忠岑",
        goroImage: "094.png",
        studyOrder: 94
    },
    {
        no: 31,
        kimariji: "あさぼらけあ",
        normal: "./torifuda/tori_31.png",
        reverse: "./torifuda/tori_r_31.png",
        goro: "あさぼらけあ よしのちゃん",
        classification: "16枚札　あ",
        upper: "朝ぼらけ 有明の月と見るまでに",
        lower: "吉野の里に 降れる白雪",
        author: "坂上是則",
        goroImage: "096.png",
        studyOrder: 96
    },
    {
        no: 32,
        kimariji: "やまが",
        normal: "./torifuda/tori_32.png",
        reverse: "./torifuda/tori_r_32.png",
        goro: "やまが ながれ",
        classification: "4枚札　はやよか",
        upper: "山川に 風のかけたる しがらみは",
        lower: "ながれもあへぬ もみぢなりけり",
        author: "春道列樹",
        goroImage: "036.png",
        studyOrder: 36
    },
    {
        no: 33,
        kimariji: "ひさ",
        normal: "./torifuda/tori_33.png",
        reverse: "./torifuda/tori_r_33.png",
        goro: "ひさしぶり しづちゃん",
        classification: "3枚札　いちひき",
        upper: "久方の 光のどけき 春の日に",
        lower: "しづ心なく 花の散るらむ",
        author: "紀友則",
        goroImage: "024.png",
        studyOrder: 24
    },
    {
        no: 34,
        kimariji: "たれ",
        normal: "./torifuda/tori_34.png",
        reverse: "./torifuda/tori_r_34.png",
        goro: "たれ まつも",
        classification: "6枚札　たこ",
        upper: "誰をかも しる人にせむ 高砂の",
        lower: "松も昔の 友ならなくに",
        author: "藤原興風",
        goroImage: "056.png",
        studyOrder: 56
    },
    {
        no: 35,
        kimariji: "ひとは",
        normal: "./torifuda/tori_35.png",
        reverse: "./torifuda/tori_r_35.png",
        goro: "ひとは はなそう",
        classification: "3枚札　いちひき",
        upper: "人はいさ 心も知らず ふるさとは",
        lower: "花ぞ昔の 香に匂ひける",
        author: "紀貫之",
        goroImage: "025.png",
        studyOrder: 25
    },
    {
        no: 36,
        kimariji: "なつ",
        normal: "./torifuda/tori_36.png",
        reverse: "./torifuda/tori_r_36.png",
        goro: "なつ くもの",
        classification: "8枚札　な",
        upper: "夏の夜は まだ宵ながら あけぬるを",
        lower: "雲のいづこに 月やどるらむ",
        author: "清原深養父",
        goroImage: "077.png",
        studyOrder: 77
    },
    {
        no: 37,
        kimariji: "しら",
        normal: "./torifuda/tori_37.png",
        reverse: "./torifuda/tori_r_37.png",
        goro: "しらがが つらい",
        classification: "2枚札　うつしもゆ",
        upper: "白露に 風の吹きしく 秋の野は",
        lower: "つらぬきとめぬ 玉ぞ散りける",
        author: "文屋朝康",
        goroImage: "012.png",
        studyOrder: 12
    },
    {
        no: 38,
        kimariji: "わすら",
        normal: "./torifuda/tori_38.png",
        reverse: "./torifuda/tori_r_38.png",
        goro: "わすら もち",
        classification: "7枚札　おわ",
        upper: "忘らるる 身をば思はず ちかひてし",
        lower: "人の命の 惜しくもあるかな",
        author: "右近",
        goroImage: "074.png",
        studyOrder: 74
    },
    {
        no: 39,
        kimariji: "あさじ",
        normal: "./torifuda/tori_39.png",
        reverse: "./torifuda/tori_r_39.png",
        goro: "あさじが あまりにいたい",
        classification: "16枚札　あ",
        upper: "浅茅生の 小野の篠原 しのぶれど",
        lower: "あまりてなどか 人の恋しき",
        author: "参議等",
        goroImage: "095.png",
        studyOrder: 95
    },
    {
        no: 40,
        kimariji: "しの",
        normal: "./torifuda/tori_40.png",
        reverse: "./torifuda/tori_r_40.png",
        goro: "しの もの",
        classification: "2枚札　うつしもゆ",
        upper: "しのぶれど 色に出でにけり 我が恋は",
        lower: "物や思ふと 人の問ふまで",
        author: "平兼盛",
        goroImage: "013.png",
        studyOrder: 13
    },
    {
        no: 41,
        kimariji: "こい",
        normal: "./torifuda/tori_41.png",
        reverse: "./torifuda/tori_r_41.png",
        goro: "こいをした ひとしくん",
        classification: "6枚札　たこ",
        upper: "恋すてふ 我が名はまだき 立ちにけり",
        lower: "人しれずこそ 思ひそめしか",
        author: "壬生忠見",
        goroImage: "058.png",
        studyOrder: 58
    },
    {
        no: 42,
        kimariji: "ちぎりき",
        normal: "./torifuda/tori_42.png",
        reverse: "./torifuda/tori_r_42.png",
        goro: "ちぎりき す",
        classification: "3枚札　いちひき",
        upper: "ちぎりきな かたみに袖を しぼりつつ",
        lower: "末の松山 波こさじとは",
        author: "清原元輔",
        goroImage: "022.png",
        studyOrder: 22
    },
    {
        no: 43,
        kimariji: "あい",
        normal: "./torifuda/tori_43.png",
        reverse: "./torifuda/tori_r_43.png",
        goro: "あい むかし",
        classification: "16枚札　あ",
        upper: "あひみての のちの心に くらぶれば",
        lower: "昔は物を 思はざりけり",
        author: "権中納言敦忠",
        goroImage: "099.png",
        studyOrder: 99
    },
    {
        no: 44,
        kimariji: "おおこ",
        normal: "./torifuda/tori_44.png",
        reverse: "./torifuda/tori_r_44.png",
        goro: "おおこわい ひとをのろわば",
        classification: "7枚札　おわ",
        upper: "あふことの たえてしなくば なかなかに",
        lower: "人をも身をも 恨みざらまし",
        author: "中納言朝忠",
        goroImage: "069.png",
        studyOrder: 69
    },
    {
        no: 45,
        kimariji: "あわれ",
        normal: "./torifuda/tori_45.png",
        reverse: "./torifuda/tori_r_45.png",
        goro: "あわれ みの",
        classification: "16枚札　あ",
        upper: "あはれとも いふべき人は 思ほえで",
        lower: "身のいたづらに なりぬべきかな",
        author: "謙徳公",
        goroImage: "086.png",
        studyOrder: 86
    },
    {
        no: 46,
        kimariji: "ゆら",
        normal: "./torifuda/tori_46.png",
        reverse: "./torifuda/tori_r_46.png",
        goro: "ゆらゆら ゆくえ",
        classification: "2枚札　うつしもゆ",
        upper: "由良のとを 渡る舟人 かぢをたえ",
        lower: "ゆくへも知らぬ 恋の道かな",
        author: "曽禰好忠",
        goroImage: "017.png",
        studyOrder: 17
    },
    {
        no: 47,
        kimariji: "やえ",
        normal: "./torifuda/tori_47.png",
        reverse: "./torifuda/tori_r_47.png",
        goro: "やえ ひえ",
        classification: "4枚札　はやよか",
        upper: "八重むぐら しげれる宿の さびしきに",
        lower: "人こそ見えね 秋は来にけり",
        author: "恵慶法師",
        goroImage: "035.png",
        studyOrder: 35
    },
    {
        no: 48,
        kimariji: "かぜを",
        normal: "./torifuda/tori_48.png",
        reverse: "./torifuda/tori_r_48.png",
        goro: "かぜを くだけ",
        classification: "4枚札　はやよか",
        upper: "風をいたみ 岩うつ波の おのれのみ",
        lower: "くだけて物を 思ふころかな",
        author: "源重之",
        goroImage: "044.png",
        studyOrder: 44
    },
    {
        no: 49,
        kimariji: "みかき",
        normal: "./torifuda/tori_49.png",
        reverse: "./torifuda/tori_r_49.png",
        goro: "みかき ひるは",
        classification: "5枚札　み",
        upper: "みかきもり 衛士のたく火の 夜はもえて",
        lower: "昼は消えつつ 物をこそ思へ",
        author: "大中臣能宣朝臣",
        goroImage: "049.png",
        studyOrder: 49
    },
    {
        no: 50,
        kimariji: "きみがためお",
        normal: "./torifuda/tori_50.png",
        reverse: "./torifuda/tori_r_50.png",
        goro: "きみがためを ながく",
        classification: "3枚札　いちひき",
        upper: "君がため 惜しからざりし いのちさへ",
        lower: "長くもがなと 思ひけるかな",
        author: "藤原義孝",
        goroImage: "029.png",
        studyOrder: 29
    },
    {
        no: 51,
        kimariji: "かく",
        normal: "./torifuda/tori_51.png",
        reverse: "./torifuda/tori_r_51.png",
        goro: "かく さし",
        classification: "4枚札　はやよか",
        upper: "かくとだに えやはいぶきの さしも草",
        lower: "さしもしらじな もゆる思ひを",
        author: "藤原実方朝臣",
        goroImage: "042.png",
        studyOrder: 42
    },
    {
        no: 52,
        kimariji: "あけ",
        normal: "./torifuda/tori_52.png",
        reverse: "./torifuda/tori_r_52.png",
        goro: "あけまして なおうらめしや",
        classification: "16枚札　あ",
        upper: "あけぬれば 暮るるものとは 知りながら",
        lower: "なほうらめしき 朝ぼらけかな",
        author: "藤原道信朝臣",
        goroImage: "100.png",
        studyOrder: 100
    },
    {
        no: 53,
        kimariji: "なげき",
        normal: "./torifuda/tori_53.png",
        reverse: "./torifuda/tori_r_53.png",
        goro: "なげき いか",
        classification: "8枚札　な",
        upper: "なげきつつ ひとりぬる夜の あくるまは",
        lower: "いかに久しき ものとかはしる",
        author: "右大将道綱母",
        goroImage: "080.png",
        studyOrder: 80
    },
    {
        no: 54,
        kimariji: "わすれ",
        normal: "./torifuda/tori_54.png",
        reverse: "./torifuda/tori_r_54.png",
        goro: "わすれ とり",
        classification: "7枚札　おわ",
        upper: "忘れじの ゆく末までは かたければ",
        lower: "今日をかぎりの いのちともがな",
        author: "儀同三司母",
        goroImage: "073.png",
        studyOrder: 73
    },
    {
        no: 55,
        kimariji: "たき",
        normal: "./torifuda/tori_55.png",
        reverse: "./torifuda/tori_r_55.png",
        goro: "たき なこ",
        classification: "6枚札　たこ",
        upper: "滝の音は たえて久しく なりぬれど",
        lower: "名こそ流れて なほ聞こえけれ",
        author: "大納言公任",
        goroImage: "055.png",
        studyOrder: 55
    },
    {
        no: 56,
        kimariji: "あらざ",
        normal: "./torifuda/tori_56.png",
        reverse: "./torifuda/tori_r_56.png",
        goro: "あらざ たこ",
        classification: "16枚札　あ",
        upper: "あらざらむ この世のほかの 思ひ出に",
        lower: "いまひとたびの あふこともがな",
        author: "和泉式部",
        goroImage: "088.png",
        studyOrder: 88
    },
    {
        no: 57,
        kimariji: "め",
        normal: "./torifuda/tori_57.png",
        reverse: "./torifuda/tori_r_57.png",
        goro: "め くもがくれ",
        classification: "1枚札　むすめふさほせ",
        upper: "めぐりあひて 見しやそれとも わかぬまに",
        lower: "雲がくれにし 夜半の月かな",
        author: "紫式部",
        goroImage: "003.png",
        studyOrder: 3
    },
    {
        no: 58,
        kimariji: "ありま",
        normal: "./torifuda/tori_58.png",
        reverse: "./torifuda/tori_r_58.png",
        goro: "ありま いてっ",
        classification: "16枚札　あ",
        upper: "ありま山 ゐなの笹原 風吹けば",
        lower: "いでそよ人を 忘れやはする",
        author: "大弐三位",
        goroImage: "093.png",
        studyOrder: 93
    },
    {
        no: 59,
        kimariji: "やす",
        normal: "./torifuda/tori_59.png",
        reverse: "./torifuda/tori_r_59.png",
        goro: "やす かったふく",
        classification: "4枚札　はやよか",
        upper: "やすらはで 寝なましものを さ夜ふけて",
        lower: "かたぶくまでの 月を見しかな",
        author: "赤染衛門",
        goroImage: "034.png",
        studyOrder: 34
    },
    {
        no: 60,
        kimariji: "おおえ",
        normal: "./torifuda/tori_60.png",
        reverse: "./torifuda/tori_r_60.png",
        goro: "おおえん まだ",
        classification: "7枚札　おわ",
        upper: "大江山 いく野の道の 遠ければ",
        lower: "まだふみもみず 天の橋立",
        author: "小式部内侍",
        goroImage: "067.png",
        studyOrder: 67
    },
    {
        no: 61,
        kimariji: "いに",
        normal: "./torifuda/tori_61.png",
        reverse: "./torifuda/tori_r_61.png",
        goro: "いに けふこ",
        classification: "3枚札　いちひき",
        upper: "いにしへの 奈良の都の 八重桜",
        lower: "けふ九重に 匂ひぬるかな",
        author: "伊勢大輔",
        goroImage: "018.png",
        studyOrder: 18
    },
    {
        no: 62,
        kimariji: "よを",
        normal: "./torifuda/tori_62.png",
        reverse: "./torifuda/tori_r_62.png",
        goro: "よを よに",
        classification: "4枚札　はやよか",
        upper: "夜をこめて 鳥のそらねは はかるとも",
        lower: "よに逢坂の 関はゆるさじ",
        author: "清少納言",
        goroImage: "038.png",
        studyOrder: 38
    },
    {
        no: 63,
        kimariji: "いまは",
        normal: "./torifuda/tori_63.png",
        reverse: "./torifuda/tori_r_63.png",
        goro: "いまは ひとつ",
        classification: "3枚札　いちひき",
        upper: "いまはただ 思ひ絶えなむ とばかりを",
        lower: "人づてならで 言ふよしもがな",
        author: "左京大夫道雅",
        goroImage: "019.png",
        studyOrder: 19
    },
    {
        no: 64,
        kimariji: "あさぼらけう",
        normal: "./torifuda/tori_64.png",
        reverse: "./torifuda/tori_r_64.png",
        goro: "あさぼらけうしろに あらわれる",
        classification: "16枚札　あ",
        upper: "朝ぼらけ 宇治の川霧 絶え絶えに",
        lower: "あらはれわたる 瀬々の網代木",
        author: "権中納言定頼",
        goroImage: "097.png",
        studyOrder: 97
    },
    {
        no: 65,
        kimariji: "うら",
        normal: "./torifuda/tori_65.png",
        reverse: "./torifuda/tori_r_65.png",
        goro: "うらの こいくちしょうゆ",
        classification: "2枚札　うつしもゆ",
        upper: "うらみわび ほさぬ袖だに あるものを",
        lower: "恋にくちなむ 名こそをしけれ",
        author: "相模",
        goroImage: "009.png",
        studyOrder: 9
    },
    {
        no: 66,
        kimariji: "もろ",
        normal: "./torifuda/tori_66.png",
        reverse: "./torifuda/tori_r_66.png",
        goro: "もろ はなよ",
        classification: "2枚札　うつしもゆ",
        upper: "もろともに あはれと思へ 山桜",
        lower: "花よりほかに 知る人もなし",
        author: "前大僧正行尊",
        goroImage: "014.png",
        studyOrder: 14
    },
    {
        no: 67,
        kimariji: "はるの",
        normal: "./torifuda/tori_67.png",
        reverse: "./torifuda/tori_r_67.png",
        goro: "はるの かい",
        classification: "4枚札　はやよか",
        upper: "春の夜の 夢ばかりなる 手枕に",
        lower: "かひなくたたむ 名こそをしけれ",
        author: "周防内侍",
        goroImage: "031.png",
        studyOrder: 31
    },
    {
        no: 68,
        kimariji: "こころに",
        normal: "./torifuda/tori_68.png",
        reverse: "./torifuda/tori_r_68.png",
        goro: "こころに こいし",
        classification: "6枚札　たこ",
        upper: "心にも あらでうき世に ながらへば",
        lower: "恋しかるべき 夜半の月かな",
        author: "三条院",
        goroImage: "062.png",
        studyOrder: 62
    },
    {
        no: 69,
        kimariji: "あらし",
        normal: "./torifuda/tori_69.png",
        reverse: "./torifuda/tori_r_69.png",
        goro: "あらしの たつたあげ",
        classification: "16枚札　あ",
        upper: "あらし吹く み室の山の もみぢばは",
        lower: "竜田の川の 錦なりけり",
        author: "能因法師",
        goroImage: "087.png",
        studyOrder: 87
    },
    {
        no: 70,
        kimariji: "さ",
        normal: "./torifuda/tori_70.png",
        reverse: "./torifuda/tori_r_70.png",
        goro: "さ いずこ",
        classification: "1枚札　むすめふさほせ",
        upper: "さびしさに 宿を立ち出でて ながむれば",
        lower: "いづこもおなじ 秋の夕ぐれ",
        author: "良選法師",
        goroImage: "005.png",
        studyOrder: 5
    },
    {
        no: 71,
        kimariji: "ゆう",
        normal: "./torifuda/tori_71.png",
        reverse: "./torifuda/tori_r_71.png",
        goro: "ゆう あし",
        classification: "2枚札　うつしもゆ",
        upper: "夕されば 門田の稲葉 おとづれて",
        lower: "蘆のまろやに 秋風ぞ吹く",
        author: "大納言経信",
        goroImage: "016.png",
        studyOrder: 16
    },
    {
        no: 72,
        kimariji: "おと",
        normal: "./torifuda/tori_72.png",
        reverse: "./torifuda/tori_r_72.png",
        goro: "おと かけ",
        classification: "7枚札　おわ",
        upper: "音に聞く 高師の浜の あだ波は",
        lower: "かけじや袖の ぬれもこそすれ",
        author: "祐子内親王家紀伊",
        goroImage: "064.png",
        studyOrder: 64
    },
    {
        no: 73,
        kimariji: "たか",
        normal: "./torifuda/tori_73.png",
        reverse: "./torifuda/tori_r_73.png",
        goro: "たかっ とやまのいえ",
        classification: "6枚札　たこ",
        upper: "高砂の をのへのさくら さきにけり",
        lower: "とやまのかすみ たたずもあらなむ",
        author: "前権中納言匡房",
        goroImage: "051.png",
        studyOrder: 51
    },
    {
        no: 74,
        kimariji: "うか",
        normal: "./torifuda/tori_74.png",
        reverse: "./torifuda/tori_r_74.png",
        goro: "うっかり はげ",
        classification: "2枚札　うつしもゆ",
        upper: "憂かりける 人を初瀬の 山おろし",
        lower: "はげしかれとは 祈らぬものを",
        author: "源俊頼朝臣",
        goroImage: "008.png",
        studyOrder: 8
    },
    {
        no: 75,
        kimariji: "ちぎりお",
        normal: "./torifuda/tori_75.png",
        reverse: "./torifuda/tori_r_75.png",
        goro: "ちぎりお あわれ",
        classification: "3枚札　いちひき",
        upper: "ちぎりおきし させもが露を いのちにて",
        lower: "あはれ今年の 秋もいぬめり",
        author: "藤原基俊",
        goroImage: "023.png",
        studyOrder: 23
    },
    {
        no: 76,
        kimariji: "わたのはらこ",
        normal: "./torifuda/tori_76.png",
        reverse: "./torifuda/tori_r_76.png",
        goro: "わたのはらこ しらなみ",
        classification: "7枚札　おわ",
        upper: "わたの原 こぎいでてみれば 久方の",
        lower: "雲いにまがふ 沖つ白波",
        author: "法性寺入道前関白太政大臣",
        goroImage: "076.png",
        studyOrder: 76
    },
    {
        no: 77,
        kimariji: "せ",
        normal: "./torifuda/tori_77.png",
        reverse: "./torifuda/tori_r_77.png",
        goro: "せ われ",
        classification: "1枚札　むすめふさほせ",
        upper: "瀬をはやみ 岩にせかるる 滝川の",
        lower: "われても末に あはむとぞ思ふ",
        author: "崇徳院",
        goroImage: "007.png",
        studyOrder: 7
    },
    {
        no: 78,
        kimariji: "あわじ",
        normal: "./torifuda/tori_78.png",
        reverse: "./torifuda/tori_r_78.png",
        goro: "あわじ いくよね",
        classification: "16枚札　あ",
        upper: "淡路島 かよふ千鳥の 鳴く声に",
        lower: "幾夜ねざめぬ 須磨の関守",
        author: "源兼昌",
        goroImage: "085.png",
        studyOrder: 85
    },
    {
        no: 79,
        kimariji: "あきか",
        normal: "./torifuda/tori_79.png",
        reverse: "./torifuda/tori_r_79.png",
        goro: "あきかん もれる",
        classification: "16枚札　あ",
        upper: "秋風に たなびく雲の たえ間より",
        lower: "もれいづる月の 影のさやけさ",
        author: "左京大夫顕輔",
        goroImage: "090.png",
        studyOrder: 90
    },
    {
        no: 80,
        kimariji: "ながか",
        normal: "./torifuda/tori_80.png",
        reverse: "./torifuda/tori_r_80.png",
        goro: "ながか みたれて",
        classification: "8枚札　な",
        upper: "長からむ 心もしらず 黒髪の",
        lower: "みだれてけさは 物をこそ思へ",
        author: "待賢門院堀河",
        goroImage: "079.png",
        studyOrder: 79
    },
    {
        no: 81,
        kimariji: "ほ",
        normal: "./torifuda/tori_81.png",
        reverse: "./torifuda/tori_r_81.png",
        goro: "ほ たた",
        classification: "1枚札　むすめふさほせ",
        upper: "ほととぎす 鳴きつる方を ながむれば",
        lower: "ただありあけの 月ぞ残れる",
        author: "後徳大寺左大臣",
        goroImage: "006.png",
        studyOrder: 6
    },
    {
        no: 82,
        kimariji: "おも",
        normal: "./torifuda/tori_82.png",
        reverse: "./torifuda/tori_r_82.png",
        goro: "おもい うきわ",
        classification: "7枚札　おわ",
        upper: "思ひわび さてもいのちは あるものを",
        lower: "憂きにたへぬは 涙なりけり",
        author: "道因法師",
        goroImage: "065.png",
        studyOrder: 65
    },
    {
        no: 83,
        kimariji: "よのなかよ",
        normal: "./torifuda/tori_83.png",
        reverse: "./torifuda/tori_r_83.png",
        goro: "よのなかよ やまのおく",
        classification: "4枚札　はやよか",
        upper: "世の中よ 道こそなけれ 思ひ入る",
        lower: "山の奥にも 鹿ぞ鳴くなる",
        author: "皇太后宮大夫俊成",
        goroImage: "041.png",
        studyOrder: 41
    },
    {
        no: 84,
        kimariji: "ながら",
        normal: "./torifuda/tori_84.png",
        reverse: "./torifuda/tori_r_84.png",
        goro: "ながら うし",
        classification: "8枚札　な",
        upper: "ながらへば またこのごろや しのばれむ",
        lower: "憂しと見し世ぞ 今は恋しき",
        author: "藤原清輔朝臣",
        goroImage: "078.png",
        studyOrder: 78
    },
    {
        no: 85,
        kimariji: "よも",
        normal: "./torifuda/tori_85.png",
        reverse: "./torifuda/tori_r_85.png",
        goro: "ようも ねえやひま",
        classification: "4枚札　はやよか",
        upper: "夜もすがら 物思ふころは 明けやらで",
        lower: "閨のひまさへ つれなかりけり",
        author: "俊恵法師",
        goroImage: "039.png",
        studyOrder: 39
    },
    {
        no: 86,
        kimariji: "なげけ",
        normal: "./torifuda/tori_86.png",
        reverse: "./torifuda/tori_r_86.png",
        goro: "なげけ かこ",
        classification: "8枚札　な",
        upper: "なげけとて 月やは物を 思はする",
        lower: "かこち顔なる わが涙かな",
        author: "西行法師",
        goroImage: "081.png",
        studyOrder: 81
    },
    {
        no: 87,
        kimariji: "む",
        normal: "./torifuda/tori_87.png",
        reverse: "./torifuda/tori_r_87.png",
        goro: "む きむき",
        classification: "1枚札　むすめふさほせ",
        upper: "村雨の 露もまだひぬ まきの葉に",
        lower: "霧たちのぼる 秋の夕ぐれ",
        author: "寂蓮法師",
        goroImage: "001.png",
        studyOrder: 1
    },
    {
        no: 88,
        kimariji: "なにわえ",
        normal: "./torifuda/tori_88.png",
        reverse: "./torifuda/tori_r_88.png",
        goro: "なにはえー みてた",
        classification: "8枚札　な",
        upper: "難波江の 蘆のかりねの ひとよゆゑ",
        lower: "みをつくしてや 恋ひわたるべき",
        author: "皇嘉門院別当",
        goroImage: "084.png",
        studyOrder: 84
    },
    {
        no: 89,
        kimariji: "たま",
        normal: "./torifuda/tori_89.png",
        reverse: "./torifuda/tori_r_89.png",
        goro: "たま しのぶ",
        classification: "6枚札　たこ",
        upper: "玉の緒よ たえなばたえね ながらへば",
        lower: "忍ぶることの 弱りもぞする",
        author: "式子内親王",
        goroImage: "054.png",
        studyOrder: 54
    },
    {
        no: 90,
        kimariji: "みせ",
        normal: "./torifuda/tori_90.png",
        reverse: "./torifuda/tori_r_90.png",
        goro: "みせが ぬれる",
        classification: "5枚札　み",
        upper: "見せばやな 雄島のあまの 袖だにも",
        lower: "ぬれにぞぬれし 色はかはらず",
        author: "殷富門院大輔",
        goroImage: "047.png",
        studyOrder: 47
    },
    {
        no: 91,
        kimariji: "きり",
        normal: "./torifuda/tori_91.png",
        reverse: "./torifuda/tori_r_91.png",
        goro: "きりぎりすの ころもはかたい",
        classification: "3枚札　いちひき",
        upper: "きりぎりす 鳴くや霜夜の さむしろに",
        lower: "衣かたしき ひとりかも寝む",
        author: "後京極摂政前太政大臣",
        goroImage: "027.png",
        studyOrder: 27
    },
    {
        no: 92,
        kimariji: "わがそ",
        normal: "./torifuda/tori_92.png",
        reverse: "./torifuda/tori_r_92.png",
        goro: "わがそで かわく",
        classification: "7枚札　おわ",
        upper: "わが袖は 潮干に見えぬ 沖の石の",
        lower: "人こそ知らね 乾く間もなし",
        author: "二条院讃岐",
        goroImage: "072.png",
        studyOrder: 72
    },
    {
        no: 93,
        kimariji: "よのなかは",
        normal: "./torifuda/tori_93.png",
        reverse: "./torifuda/tori_r_93.png",
        goro: "よのなかは あまの",
        classification: "4枚札　はやよか",
        upper: "世の中は つねにもがもな なぎさこぐ",
        lower: "あまの小舟の 綱手かなしも",
        author: "鎌倉右大臣",
        goroImage: "040.png",
        studyOrder: 40
    },
    {
        no: 94,
        kimariji: "みよ",
        normal: "./torifuda/tori_94.png",
        reverse: "./torifuda/tori_r_94.png",
        goro: "みよちゃんの ふるさと",
        classification: "5枚札　み",
        upper: "み吉野の 山の秋風 さ夜ふけて",
        lower: "ふるさと寒く 衣うつなり",
        author: "参議雅経",
        goroImage: "048.png",
        studyOrder: 48
    },
    {
        no: 95,
        kimariji: "おおけ",
        normal: "./torifuda/tori_95.png",
        reverse: "./torifuda/tori_r_95.png",
        goro: "おおけー わかった",
        classification: "7枚札　おわ",
        upper: "おほけなく うき世の民に おほふかな",
        lower: "わがたつ杣に 墨染の袖",
        author: "前大僧正慈円",
        goroImage: "068.png",
        studyOrder: 68
    },
    {
        no: 96,
        kimariji: "はなさ",
        normal: "./torifuda/tori_96.png",
        reverse: "./torifuda/tori_r_96.png",
        goro: "はなさっと ふり",
        classification: "4枚札　はやよか",
        upper: "花さそふ 嵐の庭の 雪ならで",
        lower: "ふりゆくものは わが身なりけり",
        author: "入道前太政大臣",
        goroImage: "032.png",
        studyOrder: 32
    },
    {
        no: 97,
        kimariji: "こぬ",
        normal: "./torifuda/tori_97.png",
        reverse: "./torifuda/tori_r_97.png",
        goro: "こぬ やく",
        classification: "6枚札　たこ",
        upper: "こぬ人を まつほの浦の 夕なぎに",
        lower: "焼くやもしほの 身もこがれつつ",
        author: "権中納言定家",
        goroImage: "060.png",
        studyOrder: 60
    },
    {
        no: 98,
        kimariji: "かぜそ",
        normal: "./torifuda/tori_98.png",
        reverse: "./torifuda/tori_r_98.png",
        goro: "かぜそよぐ みそ",
        classification: "4枚札　はやよか",
        upper: "風そよぐ ならの小川の 夕ぐれは",
        lower: "みそぎぞ夏の しるしなりける",
        author: "従二位家隆",
        goroImage: "045.png",
        studyOrder: 45
    },
    {
        no: 99,
        kimariji: "ひとも",
        normal: "./torifuda/tori_99.png",
        reverse: "./torifuda/tori_r_99.png",
        goro: "ひとも よをおもう",
        classification: "3枚札　いちひき",
        upper: "人もをし 人もうらめし あぢきなく",
        lower: "世を思ふゆゑに 物思ふ身は",
        author: "後鳥羽院",
        goroImage: "026.png",
        studyOrder: 26
    },
    {
        no: 100,
        kimariji: "もも",
        normal: "./torifuda/tori_100.png",
        reverse: "./torifuda/tori_r_100.png",
        goro: "もも なほあまりある",
        classification: "2枚札　うつしもゆ",
        upper: "ももしきや ふるき軒ばの しのぶにも",
        lower: "なほあまりある 昔なりけり",
        author: "順徳院",
        goroImage: "015.png",
        studyOrder: 15
    },
];
